### ISSUE TITLE
Promote Akka.Persistence to stable

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2743]
# Stable.Persistence

## Major changes

- [x] Deprecate PersistenceView (https://github.com/akkadotnet/akka.net/pull/2747)
- [x] Remove an old SQL Query (Hints based) (https://github.com/akkadotnet/akka.net/pull/2747)
- [x] Remove all protobuf2 serializers and Google.ProtocolBuffers dependency from Persistence project. (https://github.com/akkadotnet/akka.net/pull/2748)
- [x] Make all Persistence modules NetStandard compatible without any fallbacks
- [x] Rename Persistence.Testkit to Persistence.TCK (https://github.com/akkadotnet/akka.net/pull/2741)
- [x] Add PersistenceQuery, performance and serialization tests to Persistence TCK (https://github.com/akkadotnet/akka.net/pull/2741)
- [x] Persistence Query become stable
- [x] PersistenceFSM become stable and ready for production (https://github.com/akkadotnet/akka.net/pull/2593)

## Minor changes
- [ ] [Allow persisting events when recovery has completed](https://github.com/akka/akka/pull/21893) (**up-for-grabs**)
- [x] [Limit number of concurrent PersistentActor recoveries](https://github.com/akka/akka/pull/22783) (https://github.com/akkadotnet/akka.net/pull/2655)
- [x] [Recover.none should immediately carry None snapshot](https://github.com/akka/akka/pull/23043)
- [ ] [Optimize highestSequenceNr method in AtomicWrite](https://github.com/akka/akka/pull/23059) (**up-for-grabs**)
- [x] [Use snapshot-after in config for periodical snapshots in PersistentFSM](https://github.com/akka/akka/pull/22605)
- [x] Change `AllPersistenceIds` to `PersistenceIds` query
- [x] Add pluggable offset strategies to EventsByTag query (https://github.com/akkadotnet/akka.net/pull/2851)

## Racy specs
- [ ] AtLeastOnceDelivery_should_not_send_when_actor_crashes (https://github.com/akkadotnet/akka.net/issues/1752)
- [ ] LocalSnapshotStore_configured_with_a_failing_directory_name_should_throw_an_exception... (https://github.com/akkadotnet/akka.net/issues/1751)
- [ ] AtLeastOnceDelivery_must_tolerate_and_recover_from_random_failures (https://github.com/akkadotnet/akka.net/issues/2229)

## Clean-up
- [ ] Remove `context` parameter from from `AsyncWriteJournal.ReplayMessagesAsync` method
- [ ] Remove `IsDeleted` property from `IPersistentRepresentation` class
- [ ] Remove [IAsyncRecovery](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka.Persistence/Journal/AsyncRecovery.cs#L17) interface
- [ ] Remove [IMemoryMessages](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka.Persistence/Journal/MemoryJournal.cs#L24) interface

## Plugins
- [x] Sql plugins
  - [ ] Fix test `ReadJournal_query_CurrentPersistenceIds_should_not_see_new_events_after_complete`
  - [ ] Fix test `ReadJournal_query_CurrentEventsByTag_should_complete_when_no_events`
  - [ ] Select a default serializer
- [x] Redis
  - [ ] Select a default serializer (Custom Json.NET or MsgPack)
- [x] RocksDb
- Cassandra, Mongo, Postgresql, Mysql plugins become stable after v1.3

## Serialization
- `NewtonSoftJsonSerializer` will be default serializer for all persistence events 
- All persistence plugins must create their own serializers.
- Each plugin could decide which serializer use or how to store events inside a storage
- `NewtosoftJsonSerializer` is a good choice for testing purposes, but not for production. Every persistence plugin should have its own serializer, even for json
- Serializer examples
  - Json - https://github.com/alexvaluyskiy/Akka.Persistence.Redis/blob/newversion/src/Akka.Persistence.Redis/Serialization/JsonSerializer.cs
  - MsgPack - https://github.com/alexvaluyskiy/Akka.Persistence.Redis/blob/newversion/src/examples/CustomSerialization.MsgPack/Serialization/MsgPackSerializer.cs
  - Protobuf - https://github.com/alexvaluyskiy/Akka.Persistence.Redis/blob/newversion/src/examples/CustomSerialization.Protobuf/Serialization/ProtobufSerializer.cs

**Comment by alexvaluyskiy** [comment]
A couple of new ideas
- Remove `ISnapshotter` interface, since nobody implements it
- Remove `IAsyncRecovery` interface
- Remove `IMemoryMessages` interface

**Comment by Horusiath** [comment]
Some of mine:

- Make `AtLeastOnceDelivery` using `ICanTell` interface instead of `ActorPath` - this way we can abstract communication details away. For actor ref we may try to resolve an actor, for actor selection we may use actor path as it is right now. Maybe in the future we could make use of other implementations i.e. over sharded actors.

**Comment by ismaelhamed** [comment]
Regarding the PersistentView: even though @alexvaluyskiy is right in that it is stated as deprecated in the [documentation](http://getakka.net/docs/persistence/persistent-views), when it comes to the removal of stuff, a more sensible approach would be to mark them as **Obsolete** first, make people aware of it in the changelog of the next immediate release, and schedule an approximate deadline (one or two releases afterward). 

This way you give people a definite warning, and the chance to reprioritize their backlog to not get caught off-guard.

**Comment by zbynek001** [comment]
- All persistence plugins must create their own serializers.

What is the reason for this? Is the plan to abandon serializers configuration via akka.actor.serializers for persistence? 
How will it be with akka internal states & events (e.g. AtLeastOnceDeliverySnapshot, Sharding,...)? Will we have to create custom serializers/surrogates for those as well?

**Comment by alexvaluyskiy** [comment]
@zbynek001 Persistence will support Akka.Serialization. But we are planning to abandon our Protobuf2 serializers for persistence since no one using it (Sql plugins use it only for AtLeastOnceDelivery). A plugin could decide: will it use the default Akka Serialization (NewtonSoftJson) or will have their own serializer.

> How will it be with akka internal states & events (e.g. AtLeastOnceDeliverySnapshot, Sharding,...)?
We are extending the TestKit for persistence. It will have serialization tests for all default messages (AtLeastOnceDeliverySnapshot, Sharding, PersistenceFSM)

Initially, we wanted to move from `Google.ProtocolBuffers 2.4.1.555` package to the new `Google.Protobuf 3.3` in order to support NetCore. It is a breaking change.

**Comment by zbynek001** [comment]
if this is the case with serializers handling also internal events & states, do you mind if I create a PR making them public? It's no fun creating surrogates with il.Emit as I'm doing now since some are internal

**Comment by alexvaluyskiy** [comment]
Which messages do you want to make public?

**Comment by zbynek001** [comment]
So far I've run into these:
Akka.Cluster.Sharding.Shard+EntityStarted, Akka.Cluster.Sharding
Akka.Cluster.Sharding.Shard+EntityStopped, Akka.Cluster.Sharding
Akka.Cluster.Sharding.Shard+StateChange, Akka.Cluster.Sharding
Akka.Cluster.Sharding.Shard+ShardState, Akka.Cluster.Sharding
Akka.Cluster.Sharding.PersistentShardCoordinator+State, Akka.Cluster.Sharding

**Comment by alexvaluyskiy** [comment]
Make sense. Could you create an issue

**Comment by alexvaluyskiy** [comment]
@zbynek001 Sharding has default Protobuf serializers. Have you tried them?

**Comment by zbynek001** [comment]
@alexvaluyskiy Ohh, from the changes above I understood it like persistence plugins should not use the build in serializers, so they will stay?
Theoretically I could use them and I was using them some time ago, but then I've switched to custom serialization for all events to have them fully under control in case of some breaking changes.
Btw. how is it with those build-in protobuf serializers, is there a rule that they'll be always backward compatible or could there be breaking changes?

**Comment by Danthar** [comment]
Ok so we had an internal discussion about this. Which im putting up here for all to see.

## Default serializer for SQL based plugins
We decided that for now, we are going to keep using json.net as the default serializer for the SQL based plugins. This is partly due to backwards compatibility reasons. But also to keep the sql based plugins easy to setup.
Note that we do realize that in terms of performance, this is not the best choice. However choosing which serializer to use is all about trade-offs. And we expect our users to make those choices for themselves.
Thats why we also want to add some examples showing how you would implement and configure a protobuff serializer for the SQL persistence plugins.

## Suggestion for a new configuration option for Persistence plugins
We feel that the current way persistence allows for configuring your serializer is not flexible enough.
Therefore I want to add a proposal for a new configuration option.

Extend the journal and snapshot plugin configuration with a `serializer` option.
So what this will look like is this:
```

 serializers {
    myserializer = "Akka.Serialization.YourOwnSerializer, YourOwnSerializer"
 }
akka.persistence {
	journal {
		sqlite {
                     serializer: myserializer
            
```

It would look the same for the snapshot store.
This way it allows each store, to have their own serializer configured. While still being flexible enough to be changes by the user.

This serializer will be what the persistence store will use **by default**. So if you dont define anything else. Thats what it will use as its Manifest serializer (the framing message which contains the SeqId and stuff). But also as its Payload serializer (meaning: the message you are actually saving).

It will still work with serialization bindings. So if you want your payload to be serialized differently, you can still use those to specify a different serializer.
Added advantage is, is that its possible to use multiple persistence stores (multiple different journal or snapshot backends) in the same actor system. With each using their own serializer.

### What does this mean?

Not all persistence plugins use a manifest serializer. For example the SQL based plugins simply store its manifest information directly in the table. This means that its default serializer setting only works on the payload. So if you want all your messages to be serialized using something else, all you need to do is change the serializer setting for that specific SQL store.

However for example in the case of (for example) the Redis plugin, which does use a manifest serializer. It means that if you define overrides in the serialization-bindings like so:

```
serialization-bindings {
    "Akka.YourOwnType, YourOwnAssembly" = mySerializer
  }
```
The manifest information will still be serialized using the default serializer the plugin defines.

### What about the old way 

```
serialization-bindings {
       "Akka.Persistence.IPersistentRepresentation, Akka.Persistence" = mySerializer
  }
``` 
These kind of overrides should not work anymore. Because it would defeat the purpose of having a well defined serializer per persistence store.

**Comment by alexvaluyskiy** [comment]
done
