### ISSUE TITLE
Create default community health file for Akka.NET organization

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4628]
Per https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file - we can create a default community health file for the entire Akka.NET organization in one go

The way I'd like go about doing this:

1. [ ] Close out all of the other issues as part of https://github.com/akkadotnet/akka.net/projects/7 within this repository, since this is ground zero for most user issues / questions / pull requests
2. [x] Migrate all of the material created in the `.github` folder for this project over to the `.github` repository we'll create, which will contain the defaults for the entire organization
3. [x] Delete the material in this repository and see if the standards from the `.github` repository show up.

**Comment by Aaronontheweb** [comment]
Created https://github.com/akkadotnet/.github to support this
