### ISSUE TITLE
Epic: Full AOT Support for Akka.NET

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#7246]
**Is your feature request related to a problem? Please describe.**

Part of the goal for Akka.NET v1.6 is to be able to get Akka.NET to run _everywhere_:

-  Games: Unity / Godot
- Mobile: iOS / Android
- Embedded Systems
- x64 / x86
- ARM

One of the major advantages Akka.NET has over Orleans et al is our versatility - we're not dependent on external cloud infrastructure in order to run. Akka.NET's ability to run in a stand-alone .NET process with in-memory messaging is a tremendous source of value for developers. We should lean into this.

The future of .NET is to expand beyond Windows and even x64 architectures - Ahead-of-Time Compilation, "AOT," is what will open the door for Akka.NET to be able to run on an even larger number of platforms more efficiently than it can today. So for v1.6 we are putting "full AOT support" on the critical path.

## Requirements

Where are the problem areas that prevent full AOT support today? My AOT canary implementation on TurboMqtt highlights some of the big ones: https://github.com/petabridge/TurboMqtt/pull/25

- [x] #7430
- [ ] #7431
- [ ] ExpressionCompiler magic for `ReceiveActor`, `Props`, and more: see https://github.com/akkadotnet/akka.net/issues/2811 and other related issues
- [ ] Newtonsoft.Json and default `System.Object` serialization - we are already planning on moving to Roslyn Source-Generator powered serialization in v1.6, which should address this issue. See #7465
- [ ] `Props` and its use of `NewExpression` - this is a no-no. We might need to go to more basic `Func<TActor>` implementations or other ways of specifying `Props` without using a `NewExpression`. Worth noting: `NewExpression` has been a source of perf issues as well.

All of these will need to be addressed, gradually, by leveraging tools like the `Setup` class (replaces HOCON-driven `Type` loading with static-linking-friendly loading) and changing the way some of Akka.NET's built-in components attempt to load configuration.

## Things Users Need to Do To Prepare for AOT

If you care about AOT, please read the next sentences carefully:

* The default `ActorSystem.Create` experience, with no custom plugins / Akka.Remote / Akka.Cluster / Akka.Persistence et al, will be automatically AOT-friendly out of the box;
* If you are doing anything more complex than that, move onto https://github.com/akkadotnet/Akka.Hosting or https://github.com/akkadotnet/Akka.Hosting.Maui _soon_, because the upgrade experience will be fully backwards compatible if you're using either of those platforms. This will make your upgrade much simpler and easier.

If you have any other thoughts or suggestions when it comes to AOT support, please leave them here.

**Comment by evelant** [comment]
Is AOT possible at all right now? I'm learning F# with an avalonia side project and I'd like to be able to use akka on all platforms avalonia supports (web, ios, android, mac, linux, windows, even embedded).

**Comment by Aaronontheweb** [comment]
> Is AOT possible at all right now? I'm learning F# with an avalonia side project and I'd like to be able to use akka on all platforms avalonia supports (web, ios, android, mac, linux, windows, even embedded).

For core Akka yes, so long as you don't use `ReceiveActor`s - they're the biggest stumbling block. Them and the old System.ConfigurationManager bits.

**Comment by Aaronontheweb** [comment]
I updated my AOT canary solution for TurboMqtt, which uses Akka.NET and Akka.Streams https://github.com/petabridge/TurboMqtt/pull/231

**Comment by MacKey-255** [comment]
Any update?
