### ISSUE TITLE
Epic: Deprecate Akka.Persistence.Sql.Common Plugins

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#7252]
It's time folks - time to move on over to https://github.com/akkadotnet/Akka.Persistence.Sql

We even have a handy migration video that goes through all of the steps: https://www.youtube.com/watch?v=gSmqUrVHPq8

## Definitely Deprecated

Now, for the more interesting part: deprecating Akka.Persistence.Sql.Common. It's been a long time coming.

- [x] Deprecate Akka.Persistence.Sql.Common on NuGet
- [x] Deprecate Akka.Persistence.Query.Sql on NuGet
- [x] Deprecate Akka.Persistence.SqlServer + .Hosting on NuGet
- [x] Archive Akka.Persistence.SqlServer Repository
- [x] Deprecate Akka.Persistence.PostgreSql + .Hosting on NuGet
- [x] Archive Akka.Persistence.PostgreSql Repository
- [x] Deprecate Akka.Persistence.MySql + .Hosting on NuGet
- [x] Archive Akka.Persistence.MySql Repository

## Possibly Deprecated

An open question I have - what to do about Akka.Persistence.Sqlite? Linq2Db seems pretty heavy-duty for use in embedded and mobile scenarios (right, @to11mtm ?) Maybe we keep that plugin as-is and just inline the parts of Akka.Persistence.Sql.Common that it uses into it. This a matter of practicality and "what can end-users actually use on their deployment platforms," not technical purity.

**Comment by Aaronontheweb** [comment]
This will actually happen before Akka.NET v1.6, but the process will be completed by the time v1.6 ships.

**Comment by Aaronontheweb** [comment]
@Arkatufus we probably need to add the Oracle repositories to this list too
